FROM node:14.17.0
WORKDIR /usr/src/app


# RUN npm install next@11.1.1-canary.7
# RUN npm install --save prop-types
# RUN npm install -g create-next-app


# FROM node:14.15.4-alpine


# # コマンド実行
# RUN apk update && \
#     apk add git && \
#     yarn global add create-react-app