version: "3"
services:
  front-app:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app 
    command: sh -c "cd next-app && yarn dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    stdin_open: true
    volumes:
      - ./backend:/app/backend
    ports:
     - 8000:8080
    depends_on:
     - app-db
  app-db:
    image: mysql:8.0
    container_name: DB
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: docker
      MYSQL_PASSWORD: pass
